"use client";

import { useState } from "react";

const faqs = [
  {
    question: "What does a hyperbaric oxygen session feel like?",
    answer:
      'A typical session lasts 60 to 90 minutes. During the first 10-15 minutes (the "descent"), you\'ll feel a fullness in your ears similar to taking off in an airplane, and our staff will guide you through simple ear-clearing techniques. Once at pressure, you can relax, read a book, or sleep. The session ends with a slow decompression to gently return you to normal atmospheric pressure.',
  },
  {
    question: "How does this actually help my body heal?",
    answer:
      "Under normal conditions, oxygen is only carried by your red blood cells. Under hyperbaric pressure, oxygen dissolves directly into your blood plasma (the liquid part of your blood). This allows oxygen to bypass blockages and penetrate deep into damaged tissues, joints, and the brain, triggering a massive release of stem cells and fighting inflammation.",
  },
  {
    question: "How many treatments will I need to see results?",
    answer:
      "It depends entirely on your specific health goals. For general wellness, anti-aging, or athletic recovery, protocols often range from 10 to 20 sessions. For chronic conditions, problem wounds, or neurological recovery (such as TBI), clinical data suggests 40 sessions at targeted pressures yields the most profound outcomes.",
  },
  {
    question: "Is Hyperbaric Oxygen Therapy safe?",
    answer:
      "Absolutely. We use premium, FDA 510(k) cleared hard-shell chambers that meet the highest medical engineering standards. Our chambers are pressurized safely with ambient air, while highly concentrated oxygen (up to 95%) is delivered directly through a comfortable hood, maximizing safety. Our systems feature redundant pressure regulators, and a thorough medical screening is always conducted prior to your first session to ensure you have no contraindications.",
  },
  {
    question: "What do I wear during my treatment?",
    answer:
      "To ensure absolute safety, we provide specialized 100% cotton scrubs for you to change into before your session. This eliminates the risk of static electricity generated by everyday synthetic fabrics like polyester or nylon.",
  },
  {
    question: "Can I bring my phone or electronics inside?",
    answer:
      "No. For strict fire safety compliance, all battery-powered devices, cell phones, and smartwatches are prohibited inside the chamber. However, you are welcome to bring a paperback book or magazine! To ensure you are always comfortable, we provide a specialized, safety-approved walkie-talkie inside the chamber so you can communicate with our staff at any time.",
  },
];

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="faq-section">
      <div className="container">
        <div className="faq-header" data-reveal="up">
          <span className="eyebrow eyebrow-light">Common Questions</span>
          <h2>Frequently Asked Questions</h2>
          <p>
            Everything you need to know about hyperbaric oxygen therapy, our safety protocols, and what to expect during your first visit.
          </p>
        </div>

        <div className="faq-grid" data-reveal="up" data-delay="1">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`faq-item ${openIndex === index ? "open" : ""}`}
            >
              <button
                className="faq-question"
                onClick={() => toggleFAQ(index)}
                aria-expanded={openIndex === index}
              >
                <span>{faq.question}</span>
                <div className="faq-icon">
                  <div className="icon-horiz"></div>
                  <div className="icon-vert"></div>
                </div>
              </button>
              <div
                className="faq-answer-wrapper"
                style={{
                  gridTemplateRows: openIndex === index ? "1fr" : "0fr",
                }}
              >
                <div className="faq-answer">
                  <p>{faq.answer}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
